export default [
  [
    {
      key: '1',
      name: 'Оформить заказ',
      status: 'open',
      cost: '100д 45ч 50м',
      risk: 34.543,
      assignee: 'Иванов Иван Иванович',
      dateStart: '23.03.2024',
      dateEnd: '25.03.2024',
      url: 'https://www.prostospb.team/hackathon-sber24',
      dependsOn: [],
      group: 'Команда 1',
      progress: 20,
    },
    {
      key: '2',
      name: 'Просмотреть инструкцию',
      status: 'inWork',
      cost: '100д 45ч 50м',
      risk: 34.543,
      assignee: 'Сергеев Сергей Сергеевич',
      dateStart: '23.03.2024',
      dateEnd: '25.03.2024',
      url: 'https://www.prostospb.team/hackathon-sber24',
      dependsOn: [],
      group: 'Команда 2',
      progress: 45,
    },
  ],
  [
    {
      key: '3',
      name: 'Доставка',
      status: 'inWork',
      cost: '100д 45ч 50м',
      risk: 34.543,
      assignee: 'Как Такович',
      dateStart: '25.03.2024',
      dateEnd: '27.03.2024',
      url: 'https://www.prostospb.team/hackathon-sber24',
      dependsOn: ['1', '2'],
      group: 'Команда 2',
      progress: 0,
    },
    {
      key: '4',
      name: 'Собрать каркас',
      status: 'done',
      cost: '100д 45ч 50м',
      risk: 34.543,
      assignee: 'Каркасович',
      dateStart: '25.03.2024',
      dateEnd: '27.03.2024',
      url: 'https://www.prostospb.team/hackathon-sber24',
      dependsOn: [],
      group: 'Команда 1',
      progress: 1,
    },
  ],
  [
    {
      key: '5',
      name: 'Оформить заказ',
      status: 'inWork',
      cost: '100д 45ч 50м',
      risk: 34.543,
      assignee: 'Иванов Иван Иванович',
      dateStart: '23.03.2024',
      dateEnd: '25.03.2024',
      url: 'https://www.prostospb.team/hackathon-sber24',
      dependsOn: [],
      group: 'Команда 1',
      progress: 34
    },
    {
      key: '6',
      name: 'Просмотреть инструкцию',
      status: 'inWork',
      cost: '100д 45ч 50м',
      risk: 34.543,
      assignee: 'Сергеев Сергей Сергеевич',
      dateStart: '23.03.2024',
      dateEnd: '25.03.2024',
      url: 'https://www.prostospb.team/hackathon-sber24',
      dependsOn: [],
      group: 'Команда 1',
      progress: 80,
    },
  ],
  [
    {
      key: '7',
      name: 'Доставка',
      status: 'inWork',
      cost: '100д 45ч 50м',
      risk: 34.543,
      assignee: 'Как Такович',
      dateStart: '25.03.2024',
      dateEnd: '27.03.2024',
      url: 'https://www.prostospb.team/hackathon-sber24',
      dependsOn: [],
      group: 'Команда 2',
      progress: 10,
    },
    {
      key: '8',
      name: 'Собрать каркас',
      status: 'inWork',
      cost: '100д 45ч 50м',
      risk: 34.543,
      assignee: 'Каркасович',
      dateStart: '25.03.2024',
      dateEnd: '27.03.2024',
      url: 'https://www.prostospb.team/hackathon-sber24',
      dependsOn: [],
      group: 'Команда 1',
      progress: 15,
    },
  ],
]